// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateCase(ctx context.Context, arg CreateCaseParams) (EcdeCase, error)
	GetCase(ctx context.Context, id int64) (EcdeCase, error)
	ListCases(ctx context.Context, arg ListCasesParams) ([]EcdeCase, error)
}

var _ Querier = (*Queries)(nil)
